### ISSUE TITLE
Add a better way of pushing images to the server.

### ISSUE THREAD

**Issue by luckcolors** [VISIONAI/clouddream#12]
Hello.
I'm finding very difficult to push images to the server.
Can you add like a web file browser or a ftp server?(with password)
Also is possible to do something with the youtube urls?
Like in a text file we put youtube urls and the server process them.
Eg: youtube_url layertype

**Comment by Shchvova** [comment]
I still don't understand why there is no upload file button or something...

**Comment by luckcolors** [comment]
i think i simple fix for the images should be putting in the docker image an ftp server with the root directory setted on /opt/clouddream with 2 accounts:
admin could change the config files
anonymous can push images on the server.
And for the web ui there are a lot of web ftp clients so it can be easly implemented.

**Comment by quantombone** [comment]
Still need to debug the image uploader to make sure it won't cause more issues, but so far it looks like this:
![image](https://cloud.githubusercontent.com/assets/283803/8527457/b715f6fc-23da-11e5-81f2-0f4a7c07c841.png)

It is based on https://github.com/blueimp/jQuery-File-Upload and will be out within a day or two.

I can upload images from my iphone as well as drag entire collections of images from my Mac Desktop directly into the browser. This should make the people who don't like "scp/ssh" happy.

**Comment by luckcolors** [comment]
could you also put the type of inception layer for each image.
 so it can be more simple to change the inception type? :)

**Comment by gpfransen** [comment]
You can also login with an ftp client on port 22 and you are in :)
Especially for batches a lot easier.

Date: Mon, 6 Jul 2015 14:41:37 -0700

**Comment by quantombone** [comment]
I'm going to write some instructions on how to fire up an openssh container for those wanting to sftp safely into a temp container which has inputs/ and outputs/ imported as a volume. That way you can share the login info with a friend and not worry about letting unauthorized users into your main box.

Also I'll have something GUI-based ready soon. I'll make an announcement when it's ready.

**Comment by luckcolors** [comment]
OK thanks :D .

**Comment by luckcolors** [comment]
Closing for now.
