### ISSUE TITLE
Docs for using clouddream locally with boot2docker?

### ISSUE THREAD

**Issue by CallMeTuesday** [VISIONAI/clouddream#17]
Any chance we could get docs on running this locally in our own instances of docker?

Pretty please?

:) 

Thanks!!

**Comment by quantombone** [comment]
If you're on Linux, then it should work out of the box.  Are you on Mac?

**Comment by CallMeTuesday** [comment]
Yeah, I have boot2docker installed as well.

**Comment by quantombone** [comment]
There are some boot2docker instructions for another deepdream here: 
http://ryankennedy.io/running-the-deep-dream/

I won't get a chance to play with boot2docker and this repository until tomorrow night or later. If you're ambitious enough and get it running, please report back.

**Comment by quantombone** [comment]
Sorry I lied, it was really easy. Instructions for boot2docker and Mac OS X and using this repository:

https://github.com/VISIONAI/clouddream#instructions-for-mac-os-x-and-boot2docker

**Comment by bitcoinissue** [comment]
fantastic! I was trying to figure out how to do this earlier... i got it all setup and running on digital ocean and saw this haha

**Comment by ithastobe** [comment]
fantastic stuff tom! i got an instance working at digitalocean but am now running into a wall with boot2docker on os x - can't seem to figure out how to run the container and also where should i be pasting the 3 export lines per your instructions? sorry if my questions are very basic - i just started playing with docker this week to explore deepdreams...

**Comment by CallMeTuesday** [comment]
Awesome! Thanks @quantombone

**Comment by zeroasterisk** [comment]
maybe I'm wrong here, but it seems like the instructions are only using the virtualbox setup through boot2docker... not using a docker image.... no `docker run` command anywhere, though there is a `docker pull` ---- where does that get used?
