### ISSUE TITLE
Is it possible to do guided dreams in this build ?

### ISSUE THREAD

**Issue by karthikkrishnanv** [VISIONAI/clouddream#24]
Aside, the installation was really brain dead! I got it setup in 10 minutes and was able to produce my images. Thanks a lot for putting together such a clean setup. I would also love to train with my own dataset. So it would be awesome if you could support it someday.

**Comment by quantombone** [comment]
Thanks! I'm glad you found the guide useful.

When it comes to training your own models, I should warn you that **proper training on large datasets requires up to several weeks on a powerful GPU**.  While running a CPU version of these networks is good enough for producing deemdream images, training requires multiple passes over datasets that have millions of images.  This is what a lot of my colleagues at Google and MIT spend most of their days doing these days and they have really powerful computers to run multiple training experiments.

You also need a truly large dataset if you want to perform full training. Full training starts with raw pixels and learns the weights for all layers in the network.  There is however a trick to take a pretrained model and "finetune" the last few layers of the network.  This is much faster than full training and you can get away with a medium amount of data.

If you are bold enough to go this route, please check out the Caffe webpage (http://caffe.berkeleyvision.org/).  This software uses Caffe behind the scenes and it's a great software package for doing large convolutional neural network training experiments.  Plus, if you train with caffe, it will be easy to take the resulting model and import it into this demo and other deepdream demos.

**Comment by karthikkrishnanv** [comment]
Ok. Thanks. I think I am better off tabling my own training then :) I have had success in one of my hobby projects (speech synthesis) running a training for over couple of weeks on my home desktop, but this may be a different ball game. To start off, I think just getting access to a good training data is an issue. So for now, I'll just dream with whatever is available.
